# Generated by Django 2.0.6 on 2018-10-15 14:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0002_logentry_remove_auto_add'),
        ('users', '0002_auto_20181013_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional_info', models.TextField()),
                ('additional_qualification', models.ManyToManyField(related_name='seekers', to='users.Qualification')),
                ('education', models.ManyToManyField(related_name='seekers', to='users.Education')),
                ('personal_qualities', models.ManyToManyField(related_name='seekers', to='users.Quality')),
                ('skills', models.ManyToManyField(related_name='seekers', to='users.Skill')),
                ('user', models.ForeignKey(on_delete='SET_NULL', to=settings.AUTH_USER_MODEL)),
                ('work_experience', models.ManyToManyField(related_name='seekers', to='users.Company')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='additional_qualification',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='education',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='personal_qualities',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='user_ptr',
        ),
        migrations.RemoveField(
            model_name='jobseeker',
            name='work_experience',
        ),
        migrations.DeleteModel(
            name='JobSeeker',
        ),
    ]
