# Generated by Django 2.0.6 on 2018-10-15 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20181015_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resume',
            name='additional_info',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='resume',
            name='additional_qualification',
            field=models.ManyToManyField(blank=True, null=True, related_name='seekers', to='users.Qualification'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='education',
            field=models.ManyToManyField(blank=True, null=True, related_name='seekers', to='users.Education'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='personal_qualities',
            field=models.ManyToManyField(blank=True, null=True, related_name='seekers', to='users.Quality'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='skills',
            field=models.ManyToManyField(blank=True, null=True, related_name='seekers', to='users.Skill'),
        ),
        migrations.AlterField(
            model_name='resume',
            name='work_experience',
            field=models.ManyToManyField(blank=True, null=True, related_name='seekers', to='users.Company'),
        ),
    ]
